### ISSUE TITLE
Fallout from latest nixpkgs updates

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#262]
Broken packages:

* [x] chemps2
* [x] dirac
* [x] molden
* [x] qmcpack
* [x] cp2k
* [x] meep
* [x] octopus]

**Comment by sheepforce** [comment]
CP2K, meep, octopus and molden build without errors on nixpkgs/master. For those I think we can just wait some time? Or do they break by something we are doing here?

**Comment by sheepforce** [comment]
There is also some error with the optStdenv, which complains upon an update to a more recent nixpkgs version, that `NIX_CFLAGS_COMPILE` is set.

```bash
phillip@rlyeh:~/Dokumente/Git/NixOS-QChem$ nix build .#cp2k
warning: Git tree '/home/phillip/Dokumente/Git/NixOS-QChem' is dirty
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
error: The ‘env’ attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping: NIX_CFLAGS_COMPILE
(use '--show-trace' to show detailed location information)
```

**Comment by markuskowa** [comment]
The HDF5 related bugs can be fixed with the following patch (need to open an upstream PR for this).
```
diff --git a/pkgs/tools/misc/hdf5/default.nix b/pkgs/tools/misc/hdf5/default.nix
index f32fba46d55..767a545e1ee 100644
--- a/pkgs/tools/misc/hdf5/default.nix
+++ b/pkgs/tools/misc/hdf5/default.nix
@@ -91,6 +91,15 @@ stdenv.mkDerivation rec {
     moveToOutput 'bin/h5pcc' "''${!outputDev}"
   '';
 
+  postFixup = ''
+    # Remove reference to /build, which get introduced
+    # into AM_CPPFLAGS since 1.14.0
+    for i in h5cc h5c++; do
+      substituteInPlace $dev/bin/$i --replace \
+        '-I/build/hdf5-${version}/src/H5FDsubfiling' ""
+    done
+  '';
+
   passthru.tests = {
     inherit (python3.pkgs) h5py;
   };
```

**Comment by sheepforce** [comment]
> The NIX_CFLAGS_COMPILE problem is solved here: https://github.com/Nix-QChem/NixOS-QChem/pull/263

Unfortunately, it is not:

```bash
$ nix flake check
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
error: The ‘env’ attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping: NIX_CFLAGS_COMPILE
(use '--show-trace' to show detailed location information)

$ nix build .#cp2k
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
error: The ‘env’ attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping: NIX_CFLAGS_COMPILE
(use '--show-trace' to show detailed location information)
```

**Comment by markuskowa** [comment]
> Unfortunately, it is not:

Now we have a strange divergence: `nix-build release.nix -A qchem.cp2k` works just fine.
Not sure what's going on here.

**Comment by sheepforce** [comment]
But can you reproduce with `nix flake check`? I can confirm that `nix-build release.nix` works. I would just be surprised if flakes mess with the stdenv :open_mouth:

**Comment by markuskowa** [comment]
> But can you reproduce with `nix flake check`? I can confirm that `nix-build release.nix` works. I would just be surprised if flakes mess with the stdenv open_mouth

Yes, I can reproduce the failure with flakes, but I have no idea why it behaves differently. I will dig into it.

**Comment by markuskowa** [comment]
`release.nix` hides some failures away. https://github.com/Nix-QChem/NixOS-QChem/pull/264 solves the problem now. `nix flake check` proceeds, but now complains that `allow-import-from-derivation` is not activated (could be simply enabled in `nixConfig`).

**Comment by markuskowa** [comment]
Completed.
