### ISSUE TITLE
Manual build(s) / Cachix pins

### ISSUE THREAD

**Issue by FurstPlattner** [Nix-QChem/NixOS-QChem#296]
Some packages seem to be missing (?) or no longer present in the binary cache at `nix-qchem.cachix.org`. Some examples:

```
> nix path-info github:markuskowa/nixos-qchem#multiwfn
these 9 derivations will be built:
warning: Using saved setting for 'allow-import-from-derivation = true' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json
  [...]
  /nix/store/aar238xwmc3w6zyjii3v32657qd06xp9-mkl-2023.1.0.46342.drv
  /nix/store/qak9m7x4ggg6lkxnbwzw1pnvl8m04c3s-source.drv
  /nix/store/bx60z8ahw4fk55yxnd38anzvaxxc951a-multiwfn-3.8-2023-05-23.drv
these 33 paths will be fetched (18.17 MiB download, 97.88 MiB unpacked):
  [...]
error: path '/nix/store/zxp12qg2yavda0abv2nlv78v97yws76n-multiwfn-3.8-2023-05-23' is not valid

> nix path-info github:markuskowa/nixos-qchem#psi4
warning: Using saved setting for 'allow-import-from-derivation = true' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
this derivation will be built:
  /nix/store/z8y3i2ky2wll9xzmbd8cxg13slm0v3xw-python3.10-psi4-1.8.drv
error: path '/nix/store/217vmcgg8vh5r9i2qly6i7vqy2xvjrwj-python3.10-psi4-1.8' is not valid
```

On the other hand, some others work just fine:

```
> nix path-info github:markuskowa/nixos-qchem#xtb
warning: Using saved setting for 'allow-import-from-derivation = true' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
these 3 paths will be fetched (11.08 MiB download, 33.90 MiB unpacked):
  /nix/store/7idnv6x7jvbd89fghr93l8yfglgqfnnl-gfortran-11.3.0-libgcc
  /nix/store/kmjr7h9gs8c1aq90ddqa6vjs4phzv0ih-gfortran-11.3.0-lib
  /nix/store/y3yd3bxcxi5a6h4pygvypmdgvg18q2ad-xtb-6.6.0
error: path '/nix/store/y3yd3bxcxi5a6h4pygvypmdgvg18q2ad-xtb-6.6.0' is not valid
```
(I think the errors at the end can be safely ignored and are just because the path is not present on my machine…)

Entering a `nix shell` causes builds/downloads according to these reports. Is this because the packages have been garbage collected in the binary cache, or is this a user error on my side? If it is due to the cache, cachix recently added the ability to [pin certain store paths](https://blog.cachix.org/posts/2023-05-23-introducing-pins-permanent-nix-binary-storage/), saving them from the clutches of the GC.

Thank you for your time!

**Comment by markuskowa** [comment]
This sounds very much like the effect of the cachix garbage collection. The cache is running under a legacy, free account with a maximum capacity of 10 GB (big thanks to cachix). That means that older builds will fall victim to garbage collection. If you do not update your `flake.lock` file for a while, it becomes more and more likely to run into a cache miss.

The cachix pinning is a good idea, but that would only make sense for stable release branches (e.g. such as 23.05). For the rolling unstable/master branch, it would not be clear to me what paths should be pinned, without breaking the 10 GB limit.

**Comment by sheepforce** [comment]
Should we close this issue? In principle everything works as documented and we simply cannot put everything in Cachix. Unless we have a much more large scale cache I don't see another good solution except accepting cache misses.

**Comment by markuskowa** [comment]
We have optimized the cache use a little bit:
* Some outputs, such as cp2d and nwchem has been shrunk in size 
* Our internal hydra is now more selective in which builds it pushes. Builds of pull requests will not be pushed to Cachix anymore.

I hope this increases the life time of existing builds in the cache.
