### ISSUE TITLE
Broken packages with latest nixpkgs master 

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#388]
The following packages are broken (nixpkgs master: ea780f3de2d169f982564128804841500e85e373):
* [x] `python3.vermouth` (not compatible with python3Packages.pbr-6.0.0, 9b425927c4b7855d6a73883e8d47b6cd04f3ec34)
* [ ] elpa (not sure why, some tests fail, git bisect inconclusive. Probably gcc-13 related)
* [x] `amd-scalapack`: test times out.
* [x] `python3.mendeleev`:
* [x] `molcas1809`: is this still needed with SHARC-3.0?
* [x] `molden` 
* [x] `poltype2`: depency reproc, fixed in nixpkgs.
* [x] `pysisyphus`:
 `ImportError while importing test module '/build/source/tests/test_plot/test_plot.py'.`
* [x] `tests.molcas`: related to the inputs parser. Not sure what's going on here.
* [x] `vmd-python`: caused by broken upstream package `python3Packages.mesa`
* [x] `molcas`
```
not ok 1 Run-Molcas
# (in test file /nix/store/1sm0kndqiil7yqhymp6f15cbzy6s8rdc-molcas.bats, line 23)
#   `/nix/store/dvwlk0z6i4z0cgsba3zgz722094d75n9-openmolcas-23.10/bin/pymolcas -np $TEST_NUM_CPUS molcas.inp > molcas.out' failed
# Traceback (most recent call last):
#   File "<string>", line 521, in read_input
#   File "<string>", line 22, in Python_Parse
#   File "<string>", line 509, in __init__
#   File "molcas.inp", line 4
#     MCSCF/6-311G*//MCSCF/6-311G* Energy:   -113.980429893663
#               ^
# SyntaxError: invalid decimal literal
```

CC @sheepforce

**Comment by sheepforce** [comment]
> molcas1809: is this still needed with SHARC-3.0?

Nope, not required anymore.

> pysisyphus
> python3.vermouth
> tests.molcas

I can take a look on these the next days, after I'm done with my presentation :)

**Comment by sheepforce** [comment]
Hm the simplest solution may be to disable parallel building: https://github.com/NixOS/nixpkgs/blob/c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370/pkgs/applications/science/chemistry/molden/default.nix#L34C6-L34C6

Without some make packages fail, e.g. CFour also can not be built in parallel.

**Comment by sheepforce** [comment]
Pysisyphus fails because molcas fails. The molcas error is more severe, see here: https://gitlab.com/Molcas/OpenMolcas/-/issues/420 and here https://gitlab.com/Molcas/OpenMolcas/-/commit/df2d6a459b648ecf4f11f0af995e445ab7feb6b4 for a patch. Apparently pyparsing 3.11 broke some behaviour. The pysis error will disappear with a Molcas update.

**Comment by sheepforce** [comment]
The pymolcas patch can unfortunately not be applied to Molcas 23.10, directly, there is too much offset and changes inbetween. We could manually backport these changes to OpenMolcas 23.10 and vendor our own patch or we can use molcas version from master. What do you think @markuskowa ?

**Comment by markuskowa** [comment]
> The pymolcas patch can unfortunately not be applied to Molcas 23.10, directly, there is too much offset and changes inbetween. We could manually backport these changes to OpenMolcas 23.10 and vendor our own patch or we can use molcas version from master. What do you think @markuskowa ?

Yes, the original patch looks quite simple. We could create our own patch here and apply it in nixpkgs. I would prefer to unbreak molcas, since we do not know when they will tag a new release.

**Comment by sheepforce** [comment]
Fixes the original Molcas problem and Pysisyphus: https://github.com/NixOS/nixpkgs/pull/282890

**Comment by markuskowa** [comment]
This last update in January caused quite a bit of carnage. I still haven't been able to get everything back to "green" on Hydra.

* elpa will most likely remain broken until its next update. It fails a lot of tests and I do not know how to fix it.
* pysisyphus is still broken.
* vmd-python is broken because of an upstream dependency.

**Comment by sheepforce** [comment]
> pysisyphus is still broken.
> vmd-python is broken because of an upstream dependency.

I will have a look then :)

**Comment by sheepforce** [comment]
Alright, now most things should work? Do we mark Elpa as broken for the moment and close this?

**Comment by markuskowa** [comment]
> Do we mark Elpa as broken for the moment and close this?

Yes, I see no way to fix elpa for now (I have tried a bunch of things and compiler versions). It is not an essential package at the moment. I will simply comment it out in `nixpkgs-opt.nix`.
