### ISSUE TITLE
release.nix not working

### ISSUE THREAD

**Issue by alejandrogallo** [Nix-QChem/NixOS-QChem#410]
Cloning master and trying to build a release does not work:

```sh
nix-build ./release.nix -A channel
error: attribute 'channel' in selection path 'channel' not found
```

**Comment by sheepforce** [comment]
Hm, the channel is available in the  `cfg.prefix` subset, thus `nix-build ./release.nix -A qchem.channel`. But you are right, at least our README is incorrect in this case.
