### ISSUE TITLE
Cleanup of packages

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#563]
Are `mpifx` and `scalapackfx` still  need? They were initially introduced in https://github.com/Nix-QChem/NixOS-QChem/pull/250 as dependency of `dftbplus`, but got removed from its inputs in a later update.

CC @sheepforce should we keep them or drop them? They are also outdated.

**Comment by sheepforce** [comment]
I'm in favour of dropping them. Dftb+ is a little bit messy. mpifx and scalapackfx are included there now as submodules as I've never managed to convince CMake in finding them externally.
